
package Interfaz;

import Conectar.ConectarMySQL;
import Conectar.PersistenciaAvionBD;
import java.sql.Connection;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MICHELLE
 */
public class JFAvion extends javax.swing.JFrame {

    String contrasenia = "12345678";
    ConectarMySQL conexion = new ConectarMySQL();
    Connection con = conexion.getConexion("root", contrasenia);
    PersistenciaAvionBD per = new PersistenciaAvionBD();
    JFlogin login = new JFlogin();
    String idAvion;
    boolean flag;
    
    public JFAvion() {
        initComponents();
        setLocationRelativeTo(null);
        per.mostrarAviones(jTInsertarAvion, 1, "");

    }
    
    private boolean lecturaIDAvion(String comprobacion){
        boolean flag1=false;
        String patron="^(\\d{3})$";
        if(lecturaRegex(comprobacion, patron)){
            flag1=true;
        } else {
            this.jTFAvionIDActualizar.setText("");
            this.JCBaerolineaActualizar.setSelectedIndex(0);
            this.JCBmodeloActualizar.setSelectedIndex(0);
            editables();
        }
        return flag1;
    }
    
    private boolean lecturaRegex(String comprobación, String patron){
        Pattern pat= Pattern.compile(patron);
        Matcher mat= pat.matcher(comprobación);
        return mat.matches();
    }
    
    public void noEditables(){
        if(!this.jCBAvionIDActualizar.isSelected()){ this.jCBAvionIDActualizar.setEnabled(false); this.jTFAvionIDActualizar.setEnabled(false); }
        if(!this.jCBAerolineaActualizar.isSelected()){ this.jCBAerolineaActualizar.setEnabled(false); this.JCBaerolineaActualizar.setEnabled(false);}
        if(!this.jCBModeloActualizar.isSelected()){ this.jCBModeloActualizar.setEnabled(false); this.JCBmodeloActualizar.setEnabled(false); }
    }
    
    public void editables(){
        if(!this.jCBAvionIDActualizar.isSelected()){ this.jCBAvionIDActualizar.setEnabled(true); this.jTFAvionIDActualizar.setEnabled(true); }
        if(!this.jCBAerolineaActualizar.isSelected()){ this.jCBAerolineaActualizar.setEnabled(true); this.JCBaerolineaActualizar.setEnabled(true);}
        if(!this.jCBModeloActualizar.isSelected()){ this.jCBModeloActualizar.setEnabled(true); this.JCBmodeloActualizar.setEnabled(true); }
   }
    
    private void sacarDatos() {
        int itemAerolinea=0;
        int itemModelo=0;
        DefaultTableModel modeloTabla = (DefaultTableModel) jTAvionConsultar.getModel();
        idAvion = (String) modeloTabla.getValueAt(0, 0);
        for( int i=1; i<this.JCBaerolineaActualizar.getItemCount();i++){
            if(lecturaRegex(this.JCBaerolineaActualizar.getItemAt(i), (String) modeloTabla.getValueAt(0, 1))){
                itemAerolinea=i;
                break;
            }
        }  
        this.JCBaerolineaActualizar.setSelectedIndex(itemAerolinea);
        for( int i=1; i<this.JCBmodeloActualizar.getItemCount();i++){
            if(lecturaRegex(this.JCBmodeloActualizar.getItemAt(i), (String) modeloTabla.getValueAt(0, 2))){
                itemModelo=i;
                break;
            }
        }  
        this.JCBmodeloActualizar.setSelectedIndex(itemModelo);
    }
    
    private void mostrarTabla(){
        ArrayList<String> atributosMostrar = new ArrayList<>();
        ArrayList<String> nombresColumnas = new ArrayList<>();
        atributosMostrar.add("avionID"); nombresColumnas.add("ID del avion");
        if(jCBAerolineaActualizar.isSelected()){atributosMostrar.add("aerolinea"); nombresColumnas.add("Aerolinea");}
        if(jCBModeloActualizar.isSelected()){atributosMostrar.add("modelo"); nombresColumnas.add("Modelo");}
        String atributoBuscar = "avionID";
        String condicion ="'%"+JTFactualizar.getText()+"%'";
        per.consultarAvion(jTAvionActualizar,atributosMostrar, atributoBuscar, condicion, nombresColumnas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jBRegistrarAvion = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTFAvionIdInsertar = new javax.swing.JTextField();
        jCBAerolineaInsertar = new javax.swing.JComboBox<>();
        jCBModeloInsertar = new javax.swing.JComboBox<>();
        jBNuevoInsertar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTInsertarAvion = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jCBAerolineaConsultar = new javax.swing.JCheckBox();
        jCBModeloConsultar = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTFAvionIDConsultar = new javax.swing.JTextField();
        jBNuevoConsultar = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAvionConsultar = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jCBAvionIDActualizar = new javax.swing.JCheckBox();
        jCBAerolineaActualizar = new javax.swing.JCheckBox();
        jCBModeloActualizar = new javax.swing.JCheckBox();
        jTFAvionIDActualizar = new javax.swing.JTextField();
        JCBaerolineaActualizar = new javax.swing.JComboBox<>();
        JCBmodeloActualizar = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAvionActualizar = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        JTFactualizar = new javax.swing.JTextField();
        jBNuevoActualizar = new javax.swing.JButton();
        JBactualizar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTFAvionIDEliminar = new javax.swing.JTextField();
        jBEliminar = new javax.swing.JButton();
        jBNuevoEliminar = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTEliminarAvion = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AVIÓN");

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBRegistrarAvion.setText("Registrar");
        jBRegistrarAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarAvionActionPerformed(evt);
            }
        });
        jPanel1.add(jBRegistrarAvion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 97, 26));

        jPanel6.setBackground(new java.awt.Color(102, 0, 255,20));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Avion ID");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 27, -1, -1));

        jLabel5.setText("Aerolinea");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 61, -1, -1));

        jLabel6.setText("Modelo");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 101, -1, -1));

        jTFAvionIdInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFAvionIdInsertarActionPerformed(evt);
            }
        });
        jPanel6.add(jTFAvionIdInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 24, 431, -1));

        jCBAerolineaInsertar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "LATAM Airlines", "Avianca ", " " }));
        jPanel6.add(jCBAerolineaInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 58, 431, -1));

        jCBModeloInsertar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Airbus 320", "Boeing 777" }));
        jPanel6.add(jCBModeloInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 98, 431, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 530, 130));

        jBNuevoInsertar.setText("Nuevo");
        jBNuevoInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoInsertarActionPerformed(evt);
            }
        });
        jPanel1.add(jBNuevoInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 97, 26));

        jPanel7.setBackground(new java.awt.Color(51, 51, 255,20));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro"));

        jTInsertarAvion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(jTInsertarAvion);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 520, 380));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/FondoAvion.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 610));

        jTabbedPane1.addTab("Insertar", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(0, 102, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Atributos a mostrar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCBAerolineaConsultar.setText("Aerolinea");
        jPanel8.add(jCBAerolineaConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 24, 119, -1));

        jCBModeloConsultar.setText("Modelo");
        jPanel8.add(jCBModeloConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 56, 119, -1));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, 110));

        jPanel9.setBackground(new java.awt.Color(255, 102, 102,20));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Búsqueda"));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Ingrese el Avión ID");
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 24, -1, -1));

        jTFAvionIDConsultar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFAvionIDConsultarKeyReleased(evt);
            }
        });
        jPanel9.add(jTFAvionIDConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 46, 345, 26));

        jBNuevoConsultar.setText("Nuevo ");
        jBNuevoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoConsultarActionPerformed(evt);
            }
        });
        jPanel9.add(jBNuevoConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 78, 97, 26));

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 370, 120));

        jPanel10.setBackground(new java.awt.Color(255, 102, 102,20));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTAvionConsultar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTAvionConsultar);

        jPanel10.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 18, 498, 300));

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 530, 420));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/FondoAvion.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 610));

        jTabbedPane1.addTab("Consultar", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(0, 102, 204));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Atributos a actualizar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jCBAvionIDActualizar.setText("Avión ID");

        jCBAerolineaActualizar.setText("Aerolinea");

        jCBModeloActualizar.setText("Modelo");

        JCBaerolineaActualizar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "LATAM Airlines", "Avianca", " " }));

        JCBmodeloActualizar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Airbus 320", "Boeing 777" }));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jCBModeloActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JCBmodeloActualizar, 0, 163, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBAvionIDActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBAerolineaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JCBaerolineaActualizar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTFAvionIDActualizar))))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBAvionIDActualizar)
                    .addComponent(jTFAvionIDActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBAerolineaActualizar)
                    .addComponent(JCBaerolineaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBModeloActualizar)
                    .addComponent(JCBmodeloActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 150));

        jPanel4.setBackground(new java.awt.Color(255, 204, 102,20));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Registros"));

        jTAvionActualizar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTAvionActualizar);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 530, 400));

        jPanel14.setBackground(new java.awt.Color(255, 204, 51,20));
        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("Búsqueda"));

        jLabel9.setText("Ingrese el Avión ID");

        JTFactualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTFactualizarKeyReleased(evt);
            }
        });

        jBNuevoActualizar.setText("Nuevo ");
        jBNuevoActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActualizarActionPerformed(evt);
            }
        });

        JBactualizar.setText("Actualizar");
        JBactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBactualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JTFactualizar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(JBactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBNuevoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JTFactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBNuevoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 21, 240, 150));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/FondoAvion.png"))); // NOI18N
        jLabel10.setToolTipText("");
        jLabel10.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 610));

        jTabbedPane1.addTab("Actualizar", jPanel3);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(204, 255, 153,20));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro a eliminar"));

        jLabel8.setText("Ingrese el Avión ID:");

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBNuevoEliminar.setText("Nuevo");
        jBNuevoEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFAvionIDEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBNuevoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTFAvionIDEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBNuevoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jPanel13.setBackground(new java.awt.Color(255, 51, 51,20));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro"));

        jTEliminarAvion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane7.setViewportView(jTEliminarAvion);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 145, 540, 430));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/FondoAvion.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 610));

        jTabbedPane1.addTab("Eliminar", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFAvionIdInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFAvionIdInsertarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFAvionIdInsertarActionPerformed

    private void jBRegistrarAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrarAvionActionPerformed
        String avionID = this.jTFAvionIdInsertar.getText();
        String Aerolinea = (String) this.jCBAerolineaInsertar.getSelectedItem();
        String modelo = (String) this.jCBModeloInsertar.getSelectedItem();
        per.registrarAvion(avionID, Aerolinea, modelo);
        per.mostrarAviones(jTInsertarAvion, 1, "");        
    }//GEN-LAST:event_jBRegistrarAvionActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        String codigoCedula = this.jTFAvionIDEliminar.getText();
         if(per.verificacionAvion(codigoCedula)){
            per.mostrarAviones(jTAvionConsultar, 2, codigoCedula);
            sacarDatos();
            int respuesta = JOptionPane.showConfirmDialog(null,"¿Está seguro que desea eliminar el siguiente registro?\n"+
                        "ID del avión: "+idAvion+"\nAerolínea: "+JCBaerolineaActualizar.getSelectedItem()+"\nModelo: "+JCBmodeloActualizar.getSelectedItem()
                    , "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if(respuesta== JOptionPane.YES_OPTION){
                per.eliminarAvion(codigoCedula);
                per.mostrarAviones(jTEliminarAvion,1,"");
            } 
        } else {
            JOptionPane.showMessageDialog(null, "El número de avión ingresado no existe."
                    + "\nPor favor revise su entrada.","Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBNuevoEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoEliminarActionPerformed
        this.jTFAvionIDEliminar.setText("");
        this.jTFAvionIDEliminar.requestFocus();
    }//GEN-LAST:event_jBNuevoEliminarActionPerformed

    private void jTFAvionIDConsultarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFAvionIDConsultarKeyReleased
        ArrayList<String> atributosMostrar = new ArrayList<>();
        ArrayList<String> nombresColumnas = new ArrayList<>();
        atributosMostrar.add("avionID"); nombresColumnas.add("Avion ID");
        if (jCBAerolineaConsultar.isSelected()) {atributosMostrar.add("aerolinea");nombresColumnas.add("Aerolinea");}
        if (jCBModeloConsultar.isSelected()) {atributosMostrar.add("modelo"); nombresColumnas.add("Modelo");}
        String atributoBuscar = "avionID";
        String condicion = "'%" + jTFAvionIDConsultar.getText() + "%'";
        per.consultarAvion(jTAvionConsultar, atributosMostrar, atributoBuscar, condicion, nombresColumnas);
    }//GEN-LAST:event_jTFAvionIDConsultarKeyReleased

    private void jBNuevoActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActualizarActionPerformed
        this.jTFAvionIDActualizar.setText("");
        this.JTFactualizar.setText("");
        this.JCBaerolineaActualizar.setSelectedIndex(0);
        this.JCBmodeloActualizar.setSelectedIndex(0);
        if(this.jCBAvionIDActualizar.isSelected()){ this.jCBAvionIDActualizar.setSelected(false);  }
        if(this.jCBAerolineaActualizar.isSelected()){ this.jCBAerolineaActualizar.setSelected(false); }
        if(this.jCBModeloActualizar.isSelected()){ this.jCBModeloActualizar.setSelected(false); }
        this.JTFactualizar.requestFocus();
        editables();//se habilita la edición de todos los recuadros no habilitados.
    }//GEN-LAST:event_jBNuevoActualizarActionPerformed

    private void JTFactualizarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFactualizarKeyReleased
        mostrarTabla();
        if(lecturaIDAvion(this.JTFactualizar.getText())){
            String condicion =  JTFactualizar.getText() ;
            per.mostrarAviones(jTAvionConsultar, 2, condicion);
            sacarDatos();
            this.jTFAvionIDActualizar.setText(idAvion);
            jTAvionConsultar.setVisible(false);
            noEditables();
        }  
        
    }//GEN-LAST:event_JTFactualizarKeyReleased

    private void JBactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBactualizarActionPerformed
        ArrayList<String> atributosActualizar = new ArrayList<String>();
        if (jCBAvionIDActualizar.isSelected()){atributosActualizar.add("avionID= '" + jTFAvionIDActualizar.getText()+"'"); }
        if (jCBAerolineaActualizar.isSelected()){atributosActualizar.add("aerolinea= '" + JCBaerolineaActualizar.getSelectedItem() +"'"); }
        if (jCBModeloActualizar.isSelected()){atributosActualizar.add("modelo= '" + JCBmodeloActualizar.getSelectedItem()+"'"); }
        String atributoActualizar = "avionID";
        String condicion = "'" +jTFAvionIDActualizar.getText()+"'" ;
        per.actualizarAvion(atributosActualizar, atributoActualizar, condicion);
        mostrarTabla();
        this.jTFAvionIDActualizar.setEnabled(false);
        this.JCBaerolineaActualizar.setEnabled(false);
        this.JCBmodeloActualizar.setEnabled(false);
    }//GEN-LAST:event_JBactualizarActionPerformed

    private void jBNuevoInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoInsertarActionPerformed
        this.jTFAvionIdInsertar.setText("");
        this.jCBAerolineaInsertar.setSelectedIndex(0);
        this.jCBModeloInsertar.setSelectedIndex(0);
        this.jTFAvionIdInsertar.requestFocus();
    }//GEN-LAST:event_jBNuevoInsertarActionPerformed

    private void jBNuevoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoConsultarActionPerformed
        this.jTFAvionIDConsultar.setText("");
        this.jTFAvionIDConsultar.requestFocus();
    }//GEN-LAST:event_jBNuevoConsultarActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        per.mostrarAviones(jTEliminarAvion, 1,"");
        per.mostrarAviones(jTInsertarAvion, 1, "");
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFAvion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFAvion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFAvion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFAvion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFAvion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBactualizar;
    private javax.swing.JComboBox<String> JCBaerolineaActualizar;
    private javax.swing.JComboBox<String> JCBmodeloActualizar;
    private javax.swing.JTextField JTFactualizar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBNuevoActualizar;
    private javax.swing.JButton jBNuevoConsultar;
    private javax.swing.JButton jBNuevoEliminar;
    private javax.swing.JButton jBNuevoInsertar;
    private javax.swing.JButton jBRegistrarAvion;
    private javax.swing.JCheckBox jCBAerolineaActualizar;
    private javax.swing.JCheckBox jCBAerolineaConsultar;
    private javax.swing.JComboBox<String> jCBAerolineaInsertar;
    private javax.swing.JCheckBox jCBAvionIDActualizar;
    private javax.swing.JCheckBox jCBModeloActualizar;
    private javax.swing.JCheckBox jCBModeloConsultar;
    private javax.swing.JComboBox<String> jCBModeloInsertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTAvionActualizar;
    private javax.swing.JTable jTAvionConsultar;
    private javax.swing.JTable jTEliminarAvion;
    private javax.swing.JTextField jTFAvionIDActualizar;
    private javax.swing.JTextField jTFAvionIDConsultar;
    private javax.swing.JTextField jTFAvionIDEliminar;
    private javax.swing.JTextField jTFAvionIdInsertar;
    private javax.swing.JTable jTInsertarAvion;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
