package Interfaz;

import Conectar.ConectarMySQL;
import Conectar.PersistenciaClienteBD;
import java.awt.Image;
import java.awt.KeyboardFocusManager;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marck Hernández
 */
public class JFCliente extends javax.swing.JFrame {

    String contrasenia = "12345678";
    ConectarMySQL conexion = new ConectarMySQL();
    Connection con = conexion.getConexion("root", contrasenia);
    PersistenciaClienteBD perClientes = new PersistenciaClienteBD();
    CompraVuelo compra = new CompraVuelo();
    JFMenu menu = new JFMenu();
    boolean flag;
    String nombre;
    String cedula;
    String fechaNac;
    JFlogin login = new JFlogin();
    
    public JFCliente(int indentificador) {
        initComponents();
        
        setLocationRelativeTo(null);
        setIconImage(getIconImage());
        perClientes.mostrarClientes(JTregistroClientes,1,"");
        if(indentificador==2){
            JTabbedPanel.setEnabledAt(1, false);
            JTabbedPanel.setEnabledAt(2, false);
            JTabbedPanel.setEnabledAt(3, false);
            JBnuevoInsertar.setVisible(false);
            JBnuevoActualizar.setVisible(false);
            JBsiguienteCliente.setVisible(true);
            JBsiguienteActualizar.setVisible(true);
            JLpregunta.setVisible(true);
            JLclick.setVisible(true);
            login.setIdentificador(indentificador);
        } else {
            JLpregunta.setVisible(false);
            JLclick.setVisible(false);
            JBsiguienteCliente.setVisible(false);
            JBsiguienteActualizar.setVisible(false);
            JBnuevoInsertar.setVisible(true);
            JBnuevoActualizar.setVisible(true);
        }
    }

    @Override
    public Image getIconImage(){
        Image logo = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagen/LogoForm.png"));
        return logo;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTabbedPanel = new javax.swing.JTabbedPane();
        JPinsertar = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JTFnombre = new javax.swing.JTextField();
        JTFcedula = new javax.swing.JTextField();
        JCBsexo = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTregistroClientes = new javax.swing.JTable();
        JLclick = new javax.swing.JLabel();
        JBregistrar = new javax.swing.JButton();
        JBnuevoInsertar = new javax.swing.JButton();
        JLpregunta = new javax.swing.JLabel();
        JBsiguienteCliente = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        JPconsultar = new javax.swing.JPanel();
        JPatributos = new javax.swing.JPanel();
        jCBNombre = new javax.swing.JCheckBox();
        jCBFechaNac = new javax.swing.JCheckBox();
        jCBSexo = new javax.swing.JCheckBox();
        JPbusqueda = new javax.swing.JPanel();
        JTFcedulaBusq = new javax.swing.JTextField();
        JBnuevoConsultar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        JTconsultar = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        JPactualizar = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jBNombre = new javax.swing.JCheckBox();
        jBCedula = new javax.swing.JCheckBox();
        jBEdad = new javax.swing.JCheckBox();
        jBSexo = new javax.swing.JCheckBox();
        jTFCedulaActualizar = new javax.swing.JTextField();
        jTFNombreActualizar = new javax.swing.JTextField();
        JCBsexoActualizar = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        JTFcedulaAct = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        JBactualizar = new javax.swing.JButton();
        JBnuevoActualizar = new javax.swing.JButton();
        JBsiguienteActualizar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTclienteActualizar = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        JPeliminar = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        JTFcedulaEliminar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JBeliminar = new javax.swing.JButton();
        JBNuevo = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        JTclientes = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CLIENTES");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTabbedPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTabbedPanelMouseClicked(evt);
            }
        });
        JTabbedPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTabbedPanelKeyPressed(evt);
            }
        });

        JPinsertar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 102, 255,20));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabel1.setText("Nombre:");

        jLabel3.setText("Cédula:");

        jLabel4.setText("Fecha de Nacimiento:");

        jLabel5.setText("Sexo:");

        JTFnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTFnombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFnombreKeyTyped(evt);
            }
        });

        JTFcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTFcedulaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFcedulaKeyTyped(evt);
            }
        });

        JCBsexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Masculino", "Femenino", "Otro" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTFnombre)
                    .addComponent(JTFcedula)
                    .addComponent(JCBsexo, 0, 237, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JTFnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTFcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(JCBsexo)))
                .addContainerGap())
        );

        JPinsertar.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 6, -1, -1));

        jPanel3.setBackground(new java.awt.Color(204, 102, 255,20));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro"));

        JTregistroClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(JTregistroClientes);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addContainerGap())
        );

        JPinsertar.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 233, 510, 330));

        JLclick.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        JLclick.setForeground(new java.awt.Color(102, 204, 255));
        JLclick.setText("Click here");
        JLclick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLclickMouseClicked(evt);
            }
        });
        JPinsertar.add(JLclick, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        JBregistrar.setBackground(new java.awt.Color(204, 204, 255));
        JBregistrar.setText("Registrar");
        JBregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBregistrarActionPerformed(evt);
            }
        });
        JPinsertar.add(JBregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 100, 39));

        JBnuevoInsertar.setBackground(new java.awt.Color(204, 204, 255));
        JBnuevoInsertar.setText("Nuevo");
        JBnuevoInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBnuevoInsertarActionPerformed(evt);
            }
        });
        JPinsertar.add(JBnuevoInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 100, 39));

        JLpregunta.setForeground(new java.awt.Color(255, 255, 255));
        JLpregunta.setText("¿Datos mal ingresados?");
        JPinsertar.add(JLpregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 159, -1));

        JBsiguienteCliente.setText("Siguiente");
        JBsiguienteCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsiguienteClienteActionPerformed(evt);
            }
        });
        JPinsertar.add(JBsiguienteCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 100, 39));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Fondocliente.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        JPinsertar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 580));

        JTabbedPanel.addTab("Insertar", JPinsertar);

        JPconsultar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPatributos.setBackground(new java.awt.Color(153, 153, 255));
        JPatributos.setBorder(javax.swing.BorderFactory.createTitledBorder("Atributos a mostrar"));

        jCBNombre.setText("Nombre");

        jCBFechaNac.setText("Fecha Nacim.");
        jCBFechaNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBFechaNacActionPerformed(evt);
            }
        });

        jCBSexo.setText("Sexo");

        javax.swing.GroupLayout JPatributosLayout = new javax.swing.GroupLayout(JPatributos);
        JPatributos.setLayout(JPatributosLayout);
        JPatributosLayout.setHorizontalGroup(
            JPatributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPatributosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPatributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPatributosLayout.createSequentialGroup()
                        .addComponent(jCBSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPatributosLayout.createSequentialGroup()
                        .addComponent(jCBNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jCBFechaNac, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)))
        );
        JPatributosLayout.setVerticalGroup(
            JPatributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPatributosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCBNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBFechaNac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBSexo)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        JPconsultar.add(JPatributos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 160, 130));

        JPbusqueda.setBackground(new java.awt.Color(204, 153, 255,20));
        JPbusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder("Búsqueda"));

        JTFcedulaBusq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFcedulaBusqActionPerformed(evt);
            }
        });
        JTFcedulaBusq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTFcedulaBusqKeyReleased(evt);
            }
        });

        JBnuevoConsultar.setBackground(new java.awt.Color(204, 204, 255));
        JBnuevoConsultar.setText("Nuevo");
        JBnuevoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBnuevoConsultarActionPerformed(evt);
            }
        });

        jLabel6.setText("Ingrese la cédula:");

        javax.swing.GroupLayout JPbusquedaLayout = new javax.swing.GroupLayout(JPbusqueda);
        JPbusqueda.setLayout(JPbusquedaLayout);
        JPbusquedaLayout.setHorizontalGroup(
            JPbusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPbusquedaLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(JBnuevoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(JPbusquedaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(JPbusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTFcedulaBusq)
                    .addGroup(JPbusquedaLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JPbusquedaLayout.setVerticalGroup(
            JPbusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPbusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTFcedulaBusq, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBnuevoConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        JPconsultar.add(JPbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, 131));

        jPanel1.setBackground(new java.awt.Color(204, 153, 255,20));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));

        JTconsultar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(JTconsultar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addContainerGap())
        );

        JPconsultar.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 154, 520, 420));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Fondocliente.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        JPconsultar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 540, 580));

        JTabbedPanel.addTab("Consultar", JPconsultar);

        JPactualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Atributos a actualizar"));

        jBNombre.setText("Nombre");

        jBCedula.setText("Cédula");

        jBEdad.setText("Fecha Nacim.");

        jBSexo.setText("Sexo");

        JCBsexoActualizar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Masculino", "Femenino", "Otro" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jBCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFNombreActualizar)
                    .addComponent(jTFCedulaActualizar)
                    .addComponent(JCBsexoActualizar, 0, 251, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFCedulaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNombreActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JCBsexoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        JPactualizar.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 384, 162));

        jPanel5.setBackground(new java.awt.Color(204, 153, 255,20));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro a actualizar"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTFcedulaAct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTFcedulaActKeyReleased(evt);
            }
        });
        jPanel5.add(JTFcedulaAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 49, 360, 26));

        jLabel7.setText("Ingrese la cédula:");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 27, 123, -1));

        JBactualizar.setBackground(new java.awt.Color(204, 204, 255));
        JBactualizar.setText("Actualizar");
        JBactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBactualizarActionPerformed(evt);
            }
        });
        jPanel5.add(JBactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 87, 100, 29));

        JBnuevoActualizar.setBackground(new java.awt.Color(204, 204, 255));
        JBnuevoActualizar.setText("Nuevo");
        JBnuevoActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBnuevoActualizarActionPerformed(evt);
            }
        });
        jPanel5.add(JBnuevoActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 87, 100, 29));

        JBsiguienteActualizar.setText("Siguiente");
        JBsiguienteActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsiguienteActualizarActionPerformed(evt);
            }
        });
        jPanel5.add(JBsiguienteActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 87, 100, 29));

        JPactualizar.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 380, 120));

        jPanel6.setBackground(new java.awt.Color(204, 153, 255,20));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Registros "));

        JTclienteActualizar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(JTclienteActualizar);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addContainerGap())
        );

        JPactualizar.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 317, 520, 260));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Fondocliente.jpg"))); // NOI18N
        JPactualizar.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 580));

        JTabbedPanel.addTab("Actualizar", JPactualizar);

        JPeliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(153, 153, 255,20));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro a eliminar"));

        jLabel8.setText("Ingrese la cédula:");

        JBeliminar.setBackground(new java.awt.Color(204, 204, 255));
        JBeliminar.setText("Eliminar");
        JBeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBeliminarActionPerformed(evt);
            }
        });

        JBNuevo.setBackground(new java.awt.Color(204, 204, 255));
        JBNuevo.setText("Nuevo");
        JBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTFcedulaEliminar)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(JBeliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(JBNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JTFcedulaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JBeliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(JBNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        JPeliminar.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 410, -1));

        jPanel8.setBackground(new java.awt.Color(204, 153, 255,20));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Registros clientes"));

        JTclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(JTclientes);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                .addContainerGap())
        );

        JPeliminar.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 129, -1, 440));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Fondocliente.jpg"))); // NOI18N
        JPeliminar.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 580));

        JTabbedPanel.addTab("Eliminar", JPeliminar);

        getContentPane().add(JTabbedPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Método para leer que la cédula tenga 10 dígitos, este método nos ayuda a sacar los datos
     * en el Método KeyReleased de Consultar y Actualizar.
     * @param comprobacion
     * @return 
     */
    private boolean lecturaCI(String comprobacion){
        boolean flag1=false;
        String patron="^(\\d{10})$";
        if(lecturaRegex(comprobacion, patron)){
            flag1=true;
        } else {
            this.jTFCedulaActualizar.setText("");
            this.jTFNombreActualizar.setText("");
            this.JDCfechaNacActualizar.setCalendar(null);
            this.JCBsexoActualizar.setSelectedIndex(0);
            editables();
        }
        return flag1;
    }
    /**
     * Método para leer que comparar strings mediante expresiones regulares.
     * @param comprobación
     * @param patron
     * @return 
     */
    private boolean lecturaRegex(String comprobación, String patron){
        Pattern pat= Pattern.compile(patron);
        Matcher mat= pat.matcher(comprobación);
        return mat.matches();
    }
    /**
     * Método para hacer que los checkBox y los recuadros en actualizar se encuentren NO habilitados.
     */
    public void noEditables(){
        if(!this.jBCedula.isSelected()){ this.jBCedula.setEnabled(false); this.jTFCedulaActualizar.setEnabled(false); }
        if(!this.jBNombre.isSelected()){ this.jBNombre.setEnabled(false); this.jTFNombreActualizar.setEnabled(false);}
        if(!this.jBEdad.isSelected()){ this.jBEdad.setEnabled(false); this.JDCfechaNacActualizar.setEnabled(false); }
        if(!this.jBSexo.isSelected()){ this.jBSexo.setEnabled(false); this.JCBsexoActualizar.setEnabled(false);}
    }
    /**
     * Método para hacer que los checkBox y los recuadros en actualizar se encuentren habilitados.
     */
    public void editables(){
        if(!this.jBCedula.isSelected()){ this.jBCedula.setEnabled(true); this.jTFCedulaActualizar.setEnabled(true); }
        if(!this.jBNombre.isSelected()){ this.jBNombre.setEnabled(true); this.jTFNombreActualizar.setEnabled(true);}
        if(!this.jBEdad.isSelected()){ this.jBEdad.setEnabled(true); this.JDCfechaNacActualizar.setEnabled(true); }
        if(!this.jBSexo.isSelected()){ this.jBSexo.setEnabled(true); this.JCBsexoActualizar.setEnabled(true);}
    }
    /**
     * Método para sacar los datos de un cliente en base a su número de cédula.
     */
    private void sacarDatos() {
        int itemSexo=0;
        DefaultTableModel modelo = (DefaultTableModel) JTconsultar.getModel();
        cedula = (String) modelo.getValueAt(0, 0);
        nombre = (String) modelo.getValueAt(0, 1);
        fechaNac = (String) modelo.getValueAt(0, 2);
        for( int i=1; i<=this.JCBsexoActualizar.getItemCount();i++){
            if(lecturaRegex(this.JCBsexoActualizar.getItemAt(i), (String) modelo.getValueAt(0, 3))){
                itemSexo=i;
                break;
            }
        }  
        this.JCBsexoActualizar.setSelectedIndex(itemSexo);
    }
    /**
     * Método para mostrar la Tabla actualizada en la pestaña Actualizar.
     */
    private void mostrarTabla(){
        ArrayList<String> atributosMostrar = new ArrayList<>();
        ArrayList<String> nombresColumnas = new ArrayList<>();
        atributosMostrar.add("clienteID"); nombresColumnas.add("Cédula");
        if(jBNombre.isSelected()){atributosMostrar.add("Nombre"); nombresColumnas.add("Nombre");}
        if(jBEdad.isSelected()){atributosMostrar.add("Fecha"); nombresColumnas.add("Fecha Nac.");}
        if(jBSexo.isSelected()){atributosMostrar.add("Sexo"); nombresColumnas.add("Sexo");}
        String atributoBuscar = "clienteID";
        String condicion ="'%"+ JTFcedulaAct.getText()+ "%'";
        perClientes.consultarCliente(JTclienteActualizar,atributosMostrar, atributoBuscar, condicion, nombresColumnas);
    }

    
    private void jCBFechaNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBFechaNacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBFechaNacActionPerformed

    private void JTFcedulaBusqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFcedulaBusqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFcedulaBusqActionPerformed
    /**
     * Método para cuando aplastan el botón Registrar.El identificador 2 nos sirve para
     * mostrar el botón Siguiente en lugar del botón Nuevo cuando el cliente se va a registrar por primera vez.
     * @param evt 
     */
    private void JBregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBregistrarActionPerformed
        SimpleDateFormat ff = new SimpleDateFormat("dd/MM/yyyy");
        String Cedula = this.JTFcedula.getText();
        String Nombre = this.JTFnombre.getText();
        String fechaNacim = ff.format(jDCfechaNacim.getCalendar().getTime());
        String Sexo = (String) this.JCBsexo.getSelectedItem();
        perClientes.registrarCliente(Cedula, Nombre, fechaNacim, Sexo);
        perClientes.mostrarClientes(JTregistroClientes,1,"");
        if(login.getIdentificador()==2){
            flag=true;
        }        
    }//GEN-LAST:event_JBregistrarActionPerformed
    /**
     * Método para mostrar los datos de los clientes en la Tabla de la pestaña Consultar, ocurre cuando
     * se suelta una tecla que ha sido aplastada en el recuadro para buscar la cédula.
     * @param evt 
     */
    private void JTFcedulaBusqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFcedulaBusqKeyReleased
        ArrayList<String> atributosMostrar = new ArrayList<>();
        ArrayList<String> nombresColumnas = new ArrayList<>();
        atributosMostrar.add("clienteID"); nombresColumnas.add("Cédula");
        if (jCBNombre.isSelected()){atributosMostrar.add("Nombre"); nombresColumnas.add("Nombre");}
        if (jCBFechaNac.isSelected()){atributosMostrar.add("Fecha"); nombresColumnas.add("Fecha Nac.");}
        if (jCBSexo.isSelected()){atributosMostrar.add("Sexo"); nombresColumnas.add("Sexo");}
        String atributoBuscar = "clienteID";
        String condicion = "'%" + JTFcedulaBusq.getText() + "%'";
        perClientes.consultarCliente(JTconsultar,atributosMostrar, atributoBuscar, condicion, nombresColumnas);
    }//GEN-LAST:event_JTFcedulaBusqKeyReleased
    /**
     * Método para cuando aplastan el botón Eliminar, primero verifica que exista el cliente y luego lo elimina.
     * @param evt 
     */
    private void JBeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBeliminarActionPerformed
        String codigoCedula = this.JTFcedulaEliminar.getText();
         if(perClientes.verificacionCliente( codigoCedula)){
            perClientes.mostrarClientes(JTconsultar, 2, codigoCedula);
            sacarDatos();
            int respuesta = JOptionPane.showConfirmDialog(null,"¿Está seguro que desea eliminar el siguiente registro?\n"+
                        "Cédula: "+cedula+"\nNombre: "+nombre+"\nFecha de Nacimiento: "+fechaNac+"\nSexo: "+JCBsexoActualizar.getSelectedItem()
                    , "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if(respuesta== JOptionPane.YES_OPTION){
                perClientes.eliminarCliente(codigoCedula);
                perClientes.mostrarClientes(JTclientes,1,"");
            } 
        } else {
            JOptionPane.showMessageDialog(null, "El número de cédula ingresado no existe."
                    + "\nPor favor revise su entrada.","Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_JBeliminarActionPerformed
    /**
     * Método para controlar que se muestran las tablas actualizadas en las pestañas Insertar y Eliminar.
     * @param evt 
     */
    private void JTabbedPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTabbedPanelMouseClicked
        perClientes.mostrarClientes(JTclientes,1,"");
        perClientes.mostrarClientes(JTregistroClientes,1,"");
    }//GEN-LAST:event_JTabbedPanelMouseClicked
    /**
     * Método para cuando aplastan el botón Nuevo en la pestaña Eliminar.
     * @param evt 
     */
    private void JBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNuevoActionPerformed
        this.JTFcedulaEliminar.setText("");
        this.JTFcedulaEliminar.requestFocus();
        
    }//GEN-LAST:event_JBNuevoActionPerformed
    /**
     * Método para cuando aplastan el botón Actualizar, se llaman a los métodos correspondientes y se
     * bloquean los recuadros.
     * @param evt 
     */
    private void JBactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBactualizarActionPerformed
        ArrayList<String> atributosActualizar = new ArrayList<String>();
        SimpleDateFormat ff = new SimpleDateFormat("dd/MM/yyyy"); //Es necesario para poder darle el formato adecuado a la fecha.
        if (jBCedula.isSelected()){atributosActualizar.add("clienteID= '" + jTFCedulaActualizar.getText()+"'");}
        if (jBNombre.isSelected()){atributosActualizar.add("Nombre= '" + jTFNombreActualizar.getText()+"'");}
        if (jBEdad.isSelected()){atributosActualizar.add("Fecha= '" +ff.format(JDCfechaNacActualizar.getCalendar().getTime())+"'");}//Sacamos el dato ya puesto en el recuadro si se ha seleccionado la fecha.
        if (jBSexo.isSelected()){atributosActualizar.add("Sexo= '" + JCBsexoActualizar.getSelectedItem().toString()+"'");}
        String atributoActualizar = "clienteID";
        String condicion = "'" +JTFcedulaAct.getText()+"'" ;
        perClientes.actualizarCliente(atributosActualizar, atributoActualizar, condicion);
        mostrarTabla();
        this.jTFCedulaActualizar.setEnabled(false);
        this.jTFNombreActualizar.setEnabled(false);
        this.JDCfechaNacActualizar.setEnabled(false);
        this.JCBsexoActualizar.setEnabled(false);
    }//GEN-LAST:event_JBactualizarActionPerformed
    /**
     * Método para cuando aplastan el botón Nuevo en la pestaña Insertar.
     * @param evt 
     */
    private void JBnuevoInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBnuevoInsertarActionPerformed
        this.JTFcedula.setText("");
        this.JTFnombre.setText("");
        this.jDCfechaNacim.setCalendar(null);
        this.JCBsexo.setSelectedIndex(0);
        this.JTFnombre.requestFocus();
    }//GEN-LAST:event_JBnuevoInsertarActionPerformed
    /**
     * Método para cuando aplastan el botón Nuevo en la pestaña Consultar.
     * @param evt 
     */
    private void JBnuevoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBnuevoConsultarActionPerformed
        this.JTFcedulaBusq.setText("");
        this.JTFcedulaBusq.requestFocus();
    }//GEN-LAST:event_JBnuevoConsultarActionPerformed
    /**
     * Método para cuando aplastan el botón nuevo en la pestaña Actualizar.
     * @param evt 
     */
    private void JBnuevoActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBnuevoActualizarActionPerformed
        this.jTFNombreActualizar.setText("");
        this.jTFCedulaActualizar.setText("");
        this.JDCfechaNacActualizar.setCalendar(null);
        this.JTFcedulaAct.setText("");
        this.JCBsexoActualizar.setSelectedIndex(0);
        if(this.jBCedula.isSelected()){ this.jBCedula.setSelected(false);  }
        if(this.jBNombre.isSelected()){ this.jBNombre.setSelected(false); }
        if(this.jBEdad.isSelected()){ this.jBEdad.setSelected(false); }
        if(this.jBSexo.isSelected()){ this.jBSexo.setSelected(false); }
        this.jTFNombreActualizar.requestFocus();
        editables();//se habilita la edición de todos los recuadros no habilitados.
    }//GEN-LAST:event_JBnuevoActualizarActionPerformed
    /**
     * Método para salir de la ventana Cliente con ESCAPE.
     * @param evt 
     */
    private void JTabbedPanelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTabbedPanelKeyPressed
        JTabbedPanel.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, java.util.Collections.EMPTY_SET);
        if(evt.getKeyCode()==KeyEvent.VK_ESCAPE){
            this.setVisible(false);
        }
    }//GEN-LAST:event_JTabbedPanelKeyPressed
    /**
     * Método que ocurre al aplastar sobre la palabra Click here en la pestaña Ingresar.
     * @param evt 
     */
    private void JLclickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLclickMouseClicked
        if(flag){
            JTabbedPanel.setEnabledAt(2, true);
            JTabbedPanel.setEnabledAt(0, false);
            JTabbedPanel.setSelectedIndex(2);
        }
    }//GEN-LAST:event_JLclickMouseClicked
    /**
     * Método para mostrar y controlar el paso de datos a los recuadros correspondientes en la 
     * pestaña Actualizar y su habilitación para modificarse cuando la cédula ha sido ingresada por completo.
     * @param evt 
     */
    private void JTFcedulaActKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFcedulaActKeyReleased
        mostrarTabla();
        if(lecturaCI(this.JTFcedulaAct.getText())){
            String condicion = "'"+ JTFcedulaAct.getText()+"'" ;
            perClientes.mostrarClientes(JTconsultar, 2, condicion);//saca los datos a la tabla Consultar.
            try {//Necesario para controlar errores al momento de sacar la fecha.
                sacarDatos();
                SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
                this.jTFCedulaActualizar.setText(cedula);
                this.jTFNombreActualizar.setText(nombre);
                Date fecha = formatoFecha.parse(fechaNac);
                Calendar calendario = Calendar.getInstance();
                calendario.setTime(fecha);
                this.JDCfechaNacActualizar.setCalendar(calendario);
                  
            } catch (ParseException ex) {
                Logger.getLogger(JFVuelo.class.getName()).log(Level.SEVERE, null, ex);
            }
            JTconsultar.setVisible(false);
            noEditables();
        }
    }//GEN-LAST:event_JTFcedulaActKeyReleased

    private void JBsiguienteClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsiguienteClienteActionPerformed
        compra.cedula=JTFcedula.getText();
        compra.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JBsiguienteClienteActionPerformed

    private void JBsiguienteActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsiguienteActualizarActionPerformed
        compra.cedula=cedula;
        compra.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JBsiguienteActualizarActionPerformed

    private void JTFnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFnombreKeyTyped
        char variable = evt.getKeyChar();
        if (Character.isDigit(variable)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Por favor ingrese solo letras", "Advertencia",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_JTFnombreKeyTyped

    private void JTFcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFcedulaKeyTyped
        char variable = evt.getKeyChar();
        if (Character.isLetter(variable)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Por favor ingrese solo numeros", "Advertencia",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_JTFcedulaKeyTyped

    private void JTFnombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFnombreKeyPressed
        
    }//GEN-LAST:event_JTFnombreKeyPressed

    private void JTFcedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFcedulaKeyPressed
        JTFcedula.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, java.util.Collections.EMPTY_SET);
        if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_TAB){
            if(!lecturaCI(JTFcedula.getText())){
                JOptionPane.showMessageDialog(null, "Ingrese una cedula valida. \n(10 digitos)");
                this.JTFcedula.setText("");
            } else{
                this.jDCfechaNacim.requestFocus();
            }         
        }
    }//GEN-LAST:event_JTFcedulaKeyPressed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCliente(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBNuevo;
    private javax.swing.JButton JBactualizar;
    private javax.swing.JButton JBeliminar;
    private javax.swing.JButton JBnuevoActualizar;
    private javax.swing.JButton JBnuevoConsultar;
    private javax.swing.JButton JBnuevoInsertar;
    private javax.swing.JButton JBregistrar;
    private javax.swing.JButton JBsiguienteActualizar;
    private javax.swing.JButton JBsiguienteCliente;
    private javax.swing.JComboBox<String> JCBsexo;
    private javax.swing.JComboBox<String> JCBsexoActualizar;
    private javax.swing.JLabel JLclick;
    private javax.swing.JLabel JLpregunta;
    private javax.swing.JPanel JPactualizar;
    private javax.swing.JPanel JPatributos;
    private javax.swing.JPanel JPbusqueda;
    private javax.swing.JPanel JPconsultar;
    private javax.swing.JPanel JPeliminar;
    private javax.swing.JPanel JPinsertar;
    private javax.swing.JTextField JTFcedula;
    private javax.swing.JTextField JTFcedulaAct;
    private javax.swing.JTextField JTFcedulaBusq;
    private javax.swing.JTextField JTFcedulaEliminar;
    private javax.swing.JTextField JTFnombre;
    private javax.swing.JTabbedPane JTabbedPanel;
    private javax.swing.JTable JTclienteActualizar;
    private javax.swing.JTable JTclientes;
    private javax.swing.JTable JTconsultar;
    private javax.swing.JTable JTregistroClientes;
    private javax.swing.JCheckBox jBCedula;
    private javax.swing.JCheckBox jBEdad;
    private javax.swing.JCheckBox jBNombre;
    private javax.swing.JCheckBox jBSexo;
    private javax.swing.JCheckBox jCBFechaNac;
    private javax.swing.JCheckBox jCBNombre;
    private javax.swing.JCheckBox jCBSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTFCedulaActualizar;
    private javax.swing.JTextField jTFNombreActualizar;
    // End of variables declaration//GEN-END:variables
}
