package Interfaz;

import Conectar.ConectarMySQL;
import Conectar.PersistenciaClienteBD;
import java.awt.Image;
import java.sql.Connection;
import java.awt.KeyboardFocusManager;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 * @author Marck Hernández
 */
public class JFlogin extends javax.swing.JFrame {

    ConectarMySQL conexion = new ConectarMySQL();    
    private int identificador;
    private PersistenciaClienteBD perClientes = new PersistenciaClienteBD();
    private JFCliente jfcliente;
    private JFVuelo vuelo ;
    protected String cedula;
    
    public JFlogin() {
        initComponents();
        setIconImage(getIconImage());
        this.setLocationRelativeTo(null);
        this.JPlogin.setVisible(false);
        this.JPidentificacion.setVisible(false);
        
    }
    
    @Override
    public Image getIconImage(){
        Image logo = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagen/LogoForm.png"));
        return logo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        JCBopciones = new javax.swing.JComboBox<>();
        JPlogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTFusuario = new javax.swing.JTextField();
        JPFpassword = new javax.swing.JPasswordField();
        JPidentificacion = new javax.swing.JPanel();
        JTFciPasaporte = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        JBaceptar = new javax.swing.JButton();
        JBsalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de sesión");
        setBackground(new java.awt.Color(51, 0, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JCBopciones.setBackground(new java.awt.Color(204, 255, 255));
        JCBopciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Administrativo", "Cliente" }));
        JCBopciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBopcionesActionPerformed(evt);
            }
        });
        jPanel4.add(JCBopciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, 40));

        JPlogin.setBackground(new java.awt.Color(204, 255, 255,20));

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        JTFusuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFusuarioFocusLost(evt);
            }
        });
        JTFusuario.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                JTFusuarioCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                JTFusuarioInputMethodTextChanged(evt);
            }
        });
        JTFusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTFusuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFusuarioKeyTyped(evt);
            }
        });

        JPFpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JPFpasswordFocusLost(evt);
            }
        });
        JPFpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPFpasswordMouseClicked(evt);
            }
        });
        JPFpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JPFpasswordKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout JPloginLayout = new javax.swing.GroupLayout(JPlogin);
        JPlogin.setLayout(JPloginLayout);
        JPloginLayout.setHorizontalGroup(
            JPloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPloginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JTFusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(JPFpassword))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPloginLayout.setVerticalGroup(
            JPloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPloginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPFpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(JPlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 260, -1));

        JPidentificacion.setBackground(new java.awt.Color(204, 255, 255,20));

        JTFciPasaporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTFciPasaporteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTFciPasaporteKeyReleased(evt);
            }
        });

        jLabel3.setText("C.I. o Pasaporte:");

        javax.swing.GroupLayout JPidentificacionLayout = new javax.swing.GroupLayout(JPidentificacion);
        JPidentificacion.setLayout(JPidentificacionLayout);
        JPidentificacionLayout.setHorizontalGroup(
            JPidentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPidentificacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
            .addGroup(JPidentificacionLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(JTFciPasaporte)
                .addContainerGap())
        );
        JPidentificacionLayout.setVerticalGroup(
            JPidentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPidentificacionLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTFciPasaporte, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(JPidentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 260, -1));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255,20));

        JBaceptar.setText("Aceptar");
        JBaceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBaceptarMouseClicked(evt);
            }
        });
        JBaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBaceptarActionPerformed(evt);
            }
        });
        JBaceptar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JBaceptarKeyPressed(evt);
            }
        });

        JBsalir.setText("Salir");
        JBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsalirActionPerformed(evt);
            }
        });
        JBsalir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JBsalirKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(JBaceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JBsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JBaceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(JBsalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 260, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Avion-Ala.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setMaximumSize(new java.awt.Dimension(500, 700));
        jLabel5.setMinimumSize(new java.awt.Dimension(300, 500));
        jLabel5.setPreferredSize(new java.awt.Dimension(500, 700));
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String cambioCharaString(char[] cambio){
        String salida="";
        cambio=this.JPFpassword.getPassword();
        for(int i=0; i<cambio.length;i++){
            salida+=cambio[i];
        }
        return salida; 
    }
    
    public boolean lecturaCliente(){
        String condicion = this.JTFciPasaporte.getText();
        return perClientes.verificacionCliente( condicion);
    }

    private void JBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsalirActionPerformed
        System.exit(0);
        
    }//GEN-LAST:event_JBsalirActionPerformed
    
    private boolean lecturaRegex(String comprobación, String patron){
        Pattern pat= Pattern.compile(patron);
        Matcher mat= pat.matcher(comprobación);
        return mat.matches();
    }
    
    public void ejecucion(){
        jfcliente = new JFCliente(identificador);
        switch(identificador){
            case 1:
                String password = cambioCharaString(this.JPFpassword.getPassword());
                Connection con = conexion.getConexion(this.JTFusuario.getText(), password);
                this.setVisible(false);
                JOptionPane.showMessageDialog(null, "Conexión establecida con éxito");
                break;
            case 2:
                String patron="^(\\d{10})$";
                if(lecturaCliente()){
                    cedula = JTFciPasaporte.getText();
                    this.setVisible(false);
                    JOptionPane.showMessageDialog(null, "Bienvenido de nuevo");//hacer animación en cuadro de dialogo.
                } else{
                    if(lecturaRegex(this.JTFciPasaporte.getText(), patron)){
                        JOptionPane.showMessageDialog(null, "Cliente no encontrado.\nPorfavor ingrese sus datos.","Información",
                             JOptionPane.INFORMATION_MESSAGE);
                        jfcliente.setVisible(true);
                        this.setVisible(false);
                    } else {
                        JOptionPane.showMessageDialog(null, "El número ingresado debe contener 10 dígitos.","Información",
                             JOptionPane.INFORMATION_MESSAGE);
                    } 
                }
                break;
            default: 
                break;
        }

    }
    
    private void JBaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBaceptarActionPerformed
        ejecucion();
    }//GEN-LAST:event_JBaceptarActionPerformed

    public void setIdentificador(int identificador) {
        this.identificador = identificador;
    }

    
    public int getIdentificador(){
        return identificador;
    }
    
    private void JTFusuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFusuarioKeyPressed
        JTFusuario.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, java.util.Collections.EMPTY_SET);
        String texto=this.JTFusuario.getText();
        if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_TAB){
            if(texto.equals("")){
                JOptionPane.showMessageDialog(null, "Por favor ingrese el usuario",
                        "Información",JOptionPane.WARNING_MESSAGE);
            }
            else{
                this.JPFpassword.requestFocus();
            }
        }
    }//GEN-LAST:event_JTFusuarioKeyPressed

    private void JPFpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JPFpasswordKeyPressed
        JPFpassword.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, java.util.Collections.EMPTY_SET);
        if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_TAB){
            if(Arrays.equals(this.JPFpassword.getPassword(), new char[]{' '})){
                JOptionPane.showMessageDialog(null, "Por favor ingrese la clave",
                        "Información",JOptionPane.WARNING_MESSAGE);
            }
            else{
                this.JBaceptar.requestFocus();
            }
        }
    }//GEN-LAST:event_JPFpasswordKeyPressed

    private void JTFusuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFusuarioFocusLost
        
    }//GEN-LAST:event_JTFusuarioFocusLost

    private void JPFpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JPFpasswordFocusLost
        
    }//GEN-LAST:event_JPFpasswordFocusLost

    private void JTFusuarioCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_JTFusuarioCaretPositionChanged
       
    }//GEN-LAST:event_JTFusuarioCaretPositionChanged

    private void JTFusuarioInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_JTFusuarioInputMethodTextChanged
        
    }//GEN-LAST:event_JTFusuarioInputMethodTextChanged

    private void JTFusuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFusuarioKeyTyped
       
    }//GEN-LAST:event_JTFusuarioKeyTyped

    private void JPFpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPFpasswordMouseClicked
        if(this.JTFusuario.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor ingrese el usuario",
                        "Información",JOptionPane.WARNING_MESSAGE);
            this.JTFusuario.requestFocus();
        }
    }//GEN-LAST:event_JPFpasswordMouseClicked

    private void JBaceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBaceptarMouseClicked
        
    }//GEN-LAST:event_JBaceptarMouseClicked

    private void JCBopcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBopcionesActionPerformed
        switch(this.JCBopciones.getSelectedIndex()){
            case 1:
                this.JPlogin.setVisible(true);
                this.JPidentificacion.setVisible(false);
                identificador=1;
//                vuelo = new JFVuelo();
//                vuelo.setControl(true);
                break;
            case 2:
                this.JPlogin.setVisible(false);
                this.JPidentificacion.setVisible(true);
                identificador=2;
//                vuelo = new JFVuelo();
//                vuelo.setControl(true);
                break;
        }
    }//GEN-LAST:event_JCBopcionesActionPerformed
    
    private void JTFciPasaporteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFciPasaporteKeyReleased

    }//GEN-LAST:event_JTFciPasaporteKeyReleased

    private void JTFciPasaporteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFciPasaporteKeyPressed
        JTFciPasaporte.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, java.util.Collections.EMPTY_SET);
        if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_TAB){
            if("".equals(this.JTFciPasaporte.getText())){
                JOptionPane.showMessageDialog(null, "Por favor ingrese la cédula o pasaporte",
                        "Información",JOptionPane.WARNING_MESSAGE);
            }
            else{
                this.JBaceptar.requestFocus();
            }
        }
    }//GEN-LAST:event_JTFciPasaporteKeyPressed

    private void JBaceptarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JBaceptarKeyPressed
        JBaceptar.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, java.util.Collections.EMPTY_SET);
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            ejecucion();
        } else if(evt.getKeyCode()==KeyEvent.VK_TAB){
            this.JBsalir.requestFocus();
        }
    }//GEN-LAST:event_JBaceptarKeyPressed

    private void JBsalirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JBsalirKeyPressed
        JBsalir.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, java.util.Collections.EMPTY_SET);
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            this.setVisible(false);
        }
    }//GEN-LAST:event_JBsalirKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBaceptar;
    private javax.swing.JButton JBsalir;
    private javax.swing.JComboBox<String> JCBopciones;
    private javax.swing.JPasswordField JPFpassword;
    private javax.swing.JPanel JPidentificacion;
    private javax.swing.JPanel JPlogin;
    private javax.swing.JTextField JTFciPasaporte;
    private javax.swing.JTextField JTFusuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
