package Interfaz;

import java.awt.Image;
import java.awt.Toolkit;

/**
 * @author Marck Hernández
 */
public class JFMenu extends javax.swing.JFrame {

    JFlogin login = new JFlogin();
    JFVuelo vuelo;
    JFCliente cliente;
    JFAvion avion;
    CompraVuelo compra;
    protected String cedula;
    int idBoleto;
    
    public JFMenu() {
        initComponents();
        setIconImage(getIconImage());
        this.setExtendedState(MAXIMIZED_BOTH);
        this.JMItablaClientes.setVisible(false);
        this.JMITablaVuelos.setVisible(false);
        this.JMItablaAvion.setVisible(false);
        this.JMIComprarVuelo.setVisible(false);
        this.JMIComprarVuelo.setVisible(false);
    }


    @Override
    public Image getIconImage(){
        Image logo = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagen/LogoForm.png"));
        return logo;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        JBingresar = new javax.swing.JButton();
        JLimagen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JMItablaClientes = new javax.swing.JMenuItem();
        JMItablaAvion = new javax.swing.JMenuItem();
        JMITablaVuelos = new javax.swing.JMenuItem();
        JMIComprarVuelo = new javax.swing.JMenuItem();
        JMIsalir = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú principal");

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBingresar.setBackground(new java.awt.Color(204, 204, 204));
        JBingresar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        JBingresar.setText("Ingresar");
        JBingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBingresarActionPerformed(evt);
            }
        });
        jPanel2.add(JBingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 640, 170, 40));

        JLimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/fondoPortada.jpg"))); // NOI18N
        JLimagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JLimagenMouseEntered(evt);
            }
        });
        jPanel2.add(JLimagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -210, 1660, 1130));

        jMenu1.setText("Opciones");

        JMItablaClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, 0));
        JMItablaClientes.setText("Tabla clientes");
        JMItablaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMItablaClientesActionPerformed(evt);
            }
        });
        jMenu1.add(JMItablaClientes);

        JMItablaAvion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, 0));
        JMItablaAvion.setText("Tabla avion");
        JMItablaAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMItablaAvionActionPerformed(evt);
            }
        });
        jMenu1.add(JMItablaAvion);

        JMITablaVuelos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        JMITablaVuelos.setText("Tabla vuelos");
        JMITablaVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMITablaVuelosActionPerformed(evt);
            }
        });
        jMenu1.add(JMITablaVuelos);

        JMIComprarVuelo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, 0));
        JMIComprarVuelo.setText("Comprar Vuelo");
        JMIComprarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIComprarVueloActionPerformed(evt);
            }
        });
        jMenu1.add(JMIComprarVuelo);

        JMIsalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        JMIsalir.setText("Salir");
        JMIsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIsalirActionPerformed(evt);
            }
        });
        jMenu1.add(JMIsalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMITablaVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMITablaVuelosActionPerformed
        vuelo = new JFVuelo();
        vuelo.setVisible(true);
    }//GEN-LAST:event_JMITablaVuelosActionPerformed

    private void JMIsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JMIsalirActionPerformed

    private void JBingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBingresarActionPerformed
          this.login.setVisible(true);
    }//GEN-LAST:event_JBingresarActionPerformed

    private void JLimagenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLimagenMouseEntered
        int identificador = login.getIdentificador();
      
            if(identificador==1){
                this.JMItablaClientes.setVisible(true);
                this.JMItablaAvion.setVisible(true);
                this.JMITablaVuelos.setVisible(true);
                this.JBingresar.setVisible(false);
                this.JMIComprarVuelo.setVisible(false);
            } else if(identificador==2){
                cedula = login.cedula;
                this.JMIComprarVuelo.setVisible(true);
                this.JBingresar.setVisible(false);
                this.JMItablaClientes.setVisible(false);
                this.JMItablaAvion.setVisible(false);
                this.JMITablaVuelos.setVisible(false);
            } 
    }//GEN-LAST:event_JLimagenMouseEntered

    private void JMItablaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMItablaClientesActionPerformed
        cliente = new JFCliente(1);
        cliente.setVisible(true);
    }//GEN-LAST:event_JMItablaClientesActionPerformed

    private void JMItablaAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMItablaAvionActionPerformed
        avion = new JFAvion();
        avion.setVisible(true);
    }//GEN-LAST:event_JMItablaAvionActionPerformed

    private void JMIComprarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIComprarVueloActionPerformed
        compra = new CompraVuelo();
        compra.cedula=cedula;
        compra.idBoleto=idBoleto;
        compra.setVisible(true);
    }//GEN-LAST:event_JMIComprarVueloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBingresar;
    private javax.swing.JLabel JLimagen;
    private javax.swing.JMenuItem JMIComprarVuelo;
    private javax.swing.JMenuItem JMITablaVuelos;
    private javax.swing.JMenuItem JMIsalir;
    private javax.swing.JMenuItem JMItablaAvion;
    private javax.swing.JMenuItem JMItablaClientes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
