package Interfaz;

import Conectar.Asiento;
import Conectar.ListaAsientos;
import Conectar.PersistenciaAsientosBD;
import Conectar.PersistenciaAvionBD;
import Conectar.PersistenciaBoletoBD;
import Conectar.PersistenciaClienteBD;
import Conectar.PersistenciaVueloBD;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @author Marck Hernández
 */
public class VentaFinal extends javax.swing.JFrame {


    private JFMenu menu;
    private PersistenciaClienteBD cliente;
    private PersistenciaVueloBD vuelo;
    private PersistenciaAvionBD avion;
    private ListaAsientos listaAsientos;
    private PersistenciaAsientosBD perAsientos;
    private PersistenciaBoletoBD perBoleto;
    private int idBoleto=0;
    protected int numBoletos, boletosDescuento;
    protected double total;
    
    public VentaFinal(String salida, ListaAsientos asientos) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.listaAsientos = asientos;
        setIconImage(getIconImage());
        cliente = new PersistenciaClienteBD();
        vuelo=new PersistenciaVueloBD();
        avion = new PersistenciaAvionBD();
        JTAasientosEscogidos.setText(salida);
    }

    public void setIdBoleto(int idBoleto) {
        this.idBoleto = idBoleto;
    }

    
    @Override
    public Image getIconImage(){
        Image logo = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagen/LogoForm.png"));
        return logo;
    }
    
    public void imprimirTotal(){
        JLtotal.setText(String.format("%.2f",(Object) total));
    }
    
    public void sacarInformacionCliente(String cedula){
        String condicion = cedula;
        cliente.mostrarClientes(JTdatos, 2, condicion);
        JTdatos.setVisible(false);
        DefaultTableModel modelo = (DefaultTableModel) JTdatos.getModel();
        JLcedula.setText((String) modelo.getValueAt(0, 0));
        JLnombres.setText((String) modelo.getValueAt(0, 1));
        JLfechaNac.setText((String) modelo.getValueAt(0, 2));
        JLsexo.setText((String) modelo.getValueAt(0, 3));
    }
    
    public void sacarInformacionVuelo(String idVuelo) {
        String condicion = idVuelo;
        vuelo.mostrarVuelos(JTdatos, 2, condicion);
        DefaultTableModel modelo = (DefaultTableModel) JTdatos.getModel();
        JLidVuelo.setText((String) modelo.getValueAt(0, 0));
        JLidAvion.setText((String) modelo.getValueAt(0, 1));
        JLfechaSal.setText((String) modelo.getValueAt(0, 2));
        JLorigen.setText((String) modelo.getValueAt(0, 3));
        JLdestino.setText((String) modelo.getValueAt(0, 4));
        JLhora.setText((String) modelo.getValueAt(0, 5));
        sacarInformacionAvion();
    }
    
    public void sacarInformacionAvion(){
        String condicion = JLidAvion.getText();
        avion.mostrarAviones(JTdatos, 2, condicion);
        DefaultTableModel modelo = (DefaultTableModel) JTdatos.getModel();
        JLaerolinea.setText((String) modelo.getValueAt(0, 1));
        JLmodelo.setText((String) modelo.getValueAt(0, 2));
    }
    
    public void informacionBoletos(){
        String salida = "\t"+numBoletos;
        JLnumBoletos.setText(salida);
        if(boletosDescuento==0){
            jCBNo.setSelected(true);
            jCBYes.setSelected(false);
            JLbolDescuentos.setText(boletosDescuento+"");
        } else {
            jCBNo.setSelected(false);
            jCBYes.setSelected(true);
            JLbolDescuentos.setText(boletosDescuento+"");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JSdatos = new javax.swing.JScrollPane();
        JTdatos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        JLidVuelo = new javax.swing.JLabel();
        JLorigen = new javax.swing.JLabel();
        JLdestino = new javax.swing.JLabel();
        JLhora = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        JLfechaSal = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        JLnombres = new javax.swing.JLabel();
        JLcedula = new javax.swing.JLabel();
        JLfechaNac = new javax.swing.JLabel();
        JLsexo = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jCBYes = new javax.swing.JCheckBox();
        jCBNo = new javax.swing.JCheckBox();
        JLnumBoletos = new javax.swing.JLabel();
        JLbolDescuentos = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTAasientosEscogidos = new javax.swing.JTextArea();
        JBatras = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JLidAvion = new javax.swing.JLabel();
        JLmodelo = new javax.swing.JLabel();
        JLaerolinea = new javax.swing.JLabel();
        JBcancelar = new javax.swing.JButton();
        JBcomprar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        JLtotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        JTdatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        JSdatos.setViewportView(JTdatos);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Finalizar compra");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(109, 174, 230,150));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Información del vuelo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("ID vuelo:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Origen:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Destino:");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setText("Hora:");

        JLidVuelo.setBackground(new java.awt.Color(255, 255, 255));
        JLidVuelo.setOpaque(true);

        JLorigen.setBackground(new java.awt.Color(255, 255, 255));
        JLorigen.setOpaque(true);

        JLdestino.setBackground(new java.awt.Color(255, 255, 255));
        JLdestino.setOpaque(true);

        JLhora.setBackground(new java.awt.Color(255, 255, 255));
        JLhora.setOpaque(true);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel22.setText("Fecha Sal.:");

        JLfechaSal.setBackground(new java.awt.Color(255, 255, 255));
        JLfechaSal.setOpaque(true);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JLidVuelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLorigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLdestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLhora, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(JLfechaSal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JLidVuelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JLfechaSal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLorigen, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLdestino, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLhora, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 370, -1));

        jPanel9.setBackground(new java.awt.Color(109, 174, 230,150));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Información del cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Nombres:");
        jPanel9.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 19, 122, 23));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Cédula o Pasaporte:");
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 53, 122, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Fecha de nacimiento:");
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 81, -1, 22));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Sexo:");
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 109, 122, 22));

        JLnombres.setBackground(new java.awt.Color(255, 255, 255));
        JLnombres.setOpaque(true);
        jPanel9.add(JLnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 25, 235, 22));

        JLcedula.setBackground(new java.awt.Color(255, 255, 255));
        JLcedula.setOpaque(true);
        jPanel9.add(JLcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 53, 235, 22));

        JLfechaNac.setBackground(new java.awt.Color(255, 255, 255));
        JLfechaNac.setOpaque(true);
        jPanel9.add(JLfechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 81, 235, 22));

        JLsexo.setBackground(new java.awt.Color(255, 255, 255));
        JLsexo.setOpaque(true);
        jPanel9.add(JLsexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 109, 235, 22));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 190));

        jPanel12.setBackground(new java.awt.Color(109, 174, 230,150));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Información sobre la compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel19.setText("Número de boletos:");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel20.setText("Descuento:");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel21.setText("Boletos con descuento:");

        jCBYes.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCBYes.setText("Sí");
        jCBYes.setEnabled(false);
        jCBYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBYesActionPerformed(evt);
            }
        });

        jCBNo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCBNo.setText("No");
        jCBNo.setEnabled(false);

        JLnumBoletos.setBackground(new java.awt.Color(255, 255, 255));
        JLnumBoletos.setOpaque(true);

        JLbolDescuentos.setBackground(new java.awt.Color(255, 255, 255));
        JLbolDescuentos.setOpaque(true);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBYes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBNo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15))
                    .addComponent(JLbolDescuentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLnumBoletos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLnumBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jCBYes)
                    .addComponent(jCBNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLbolDescuentos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 220, 180));

        jPanel5.setBackground(new java.awt.Color(109, 174, 230,150));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Asientos Escogidos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        JTAasientosEscogidos.setEditable(false);
        JTAasientosEscogidos.setColumns(20);
        JTAasientosEscogidos.setRows(5);
        jScrollPane2.setViewportView(JTAasientosEscogidos);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 370, 280));

        JBatras.setText("<< Atrás");
        JBatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBatrasActionPerformed(evt);
            }
        });
        jPanel1.add(JBatras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 125, 35));

        jPanel11.setBackground(new java.awt.Color(109, 174, 230,150));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Datos del avión", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel5.setText("ID avión:");

        jLabel6.setText("Aerolínea:");

        jLabel7.setText("Modelo:");

        JLidAvion.setBackground(new java.awt.Color(255, 255, 255));
        JLidAvion.setOpaque(true);

        JLmodelo.setBackground(new java.awt.Color(255, 255, 255));
        JLmodelo.setOpaque(true);

        JLaerolinea.setBackground(new java.awt.Color(255, 255, 255));
        JLaerolinea.setOpaque(true);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLidAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLaerolinea, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLidAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(JLaerolinea, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JLmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 180, 180));

        JBcancelar.setText("Cancelar");
        JBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBcancelarActionPerformed(evt);
            }
        });
        jPanel1.add(JBcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 125, 35));

        JBcomprar.setText("Comprar");
        JBcomprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBcomprarActionPerformed(evt);
            }
        });
        jPanel1.add(JBcomprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 125, 35));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total a pagar:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, -1, -1));

        JLtotal.setBackground(new java.awt.Color(255, 255, 255));
        JLtotal.setOpaque(true);
        jPanel1.add(JLtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 250, 22));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/VentaFFondo.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBYesActionPerformed

    private void JBatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBatrasActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_JBatrasActionPerformed

    private void JBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBcancelarActionPerformed
        perAsientos = new PersistenciaAsientosBD();
        for(Asiento aux: listaAsientos.getAsientosEscogidos()){
            perAsientos.actualizarAsiento(aux.getNumeroAsiento(), JLidAvion.getText(), "Disponible");
        }
        System.exit(0);
    }//GEN-LAST:event_JBcancelarActionPerformed

    private void JBcomprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBcomprarActionPerformed
        perAsientos = new PersistenciaAsientosBD();
        perBoleto = new PersistenciaBoletoBD();
        String idAsientos="";
        for(Asiento aux: listaAsientos.getAsientosEscogidos()){
            idAsientos+= aux.getNumeroAsiento()+"\n";
        }        
        int opcion = JOptionPane.showConfirmDialog(null, "Está seguro que desea realizar la siguiente compra: \n"+
                "Cédula: "+JLcedula.getText()+"\nID del vuelo: "+JLidVuelo.getText()+"\nID del avión: "+JLidAvion.getText()+
                        "\nID Asientos: "+idAsientos+"\nPrecio: "+JLtotal.getText());
        if(opcion == JOptionPane.YES_OPTION){
            for(Asiento aux: listaAsientos.getAsientosEscogidos()){
                perAsientos.actualizarAsiento(aux.getNumeroAsiento(), JLidAvion.getText(), "Ocupado");
                idBoleto++;
                perBoleto.registrarBoleto(String.valueOf(idBoleto), JLcedula.getText(), JLidVuelo.getText(), aux.getNumeroAsiento());
                JOptionPane.showMessageDialog(null, "Su compra fue realizada con éxito");
                menu = new JFMenu();
                menu.idBoleto=idBoleto;
                this.setVisible(false);
                menu.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Transacción cancelada");
        }
 
        
        
    }//GEN-LAST:event_JBcomprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentaFinal(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBatras;
    private javax.swing.JButton JBcancelar;
    private javax.swing.JButton JBcomprar;
    private javax.swing.JLabel JLaerolinea;
    private javax.swing.JLabel JLbolDescuentos;
    private javax.swing.JLabel JLcedula;
    private javax.swing.JLabel JLdestino;
    private javax.swing.JLabel JLfechaNac;
    private javax.swing.JLabel JLfechaSal;
    private javax.swing.JLabel JLhora;
    private javax.swing.JLabel JLidAvion;
    private javax.swing.JLabel JLidVuelo;
    private javax.swing.JLabel JLmodelo;
    private javax.swing.JLabel JLnombres;
    private javax.swing.JLabel JLnumBoletos;
    private javax.swing.JLabel JLorigen;
    private javax.swing.JLabel JLsexo;
    private javax.swing.JLabel JLtotal;
    private javax.swing.JScrollPane JSdatos;
    private javax.swing.JTextArea JTAasientosEscogidos;
    private javax.swing.JTable JTdatos;
    private javax.swing.JCheckBox jCBNo;
    private javax.swing.JCheckBox jCBYes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
